version: 2

jobs:
    build:
        docker:
            - image: nicolov/gazebo-headless-docker:0.0.2
        steps:
            - checkout
            # The actual test is whether the video file was created
            - run:
                scripts/run-demo.sh || file out/demo.mkv
            - store_artifacts:
                path: out

